### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by trancong12102** [zombiies/zombiies-api#1]
- [x] Init base project
- Core module:
  - [x] Interactive with smart contract
  - [x] Intractive with ipfs storage
- [x] API authentication
- [x] API profile
- [x] API card
- [x] API auction
- [x] API deck
- [x] API notification
- [ ] API wait list
- [ ] API in game
- [ ] API reward
